tickets/urls.py
from django.urls import path
from .import views
from .views import add_to_cart, remove_to_cart, remove_single_ticket_to_cart, Category_detail, ChartData
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'tickets'

urlpatterns = [
    # ticket/api/view/
    path('tickets/api/view/', views.TicketsApi.as_view()),
    # tickets/list/
    path('all-tickets/', views.ticket_list_filter, name='list_view'),
    # tickets/affiliate/help/
    path('affiliate/help/', views.Affiliate_help.as_view(), name='affiliate_help'),
    # # tickets/team/
    # path('team/', views.About_us.as_view(), name='team'),
    # # tickets/team/
    # path('blog/', views.Blog.as_view(), name='blog'),
    # tickets/5/details/
    path('<int:pk>/details/', views.Ticket_details.as_view(), name='ticket_detail'),
    # tickets/create/
    path('create/', views.Create_ticket.as_view(), name='create_ticket'),
    # tickets/5/update/
    path('<int:pk>/update/', views.Update_ticket.as_view(), name='update_ticket'),
    # tickets/5/delete/
    path('<int:pk>/delete/', views.Delete_ticket.as_view(), name='delete_ticket'),
    # tickets/help/affiliate/
    path('help/', views.Main_help.as_view(), name='main_help'),
    # tickets/add/cart/
    path('<int:pk>/add/cart/', add_to_cart, name='add_cart'),
    # tickets/remove/cart/
    path('<int:pk>/remove/cart/', remove_to_cart, name='remove_cart'),
    #tickets/order-summary/
    path('order/summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    # tickets/remove/cart/
    path('<int:pk>/remove/ticket/cart/', remove_single_ticket_to_cart, name='remove_single_ticket_cart'),
    #tickets/checkout/
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    #category/cinema/
    path('category/<str:slug>/', Category_detail, name='category'),
    path('category/cinema/', Category_detail, name='category_cinema'),
    path('category/sport/', Category_detail, name='category_sport'),
    path('category/concert/', Category_detail, name='category_concert'),
    path('category/expo/', Category_detail, name='category_expo'),
    path('category/meeting/', Category_detail, name='category_meeting'),
    path('category/others/', Category_detail, name='category_others'),
    path('category/festival/', Category_detail, name='category_festival'),
    path('api/data/', ChartData.as_view(), name='dash-api'),
    path('dashboard/', views.DashView.as_view(), name='dashboard_affiliates'),



]

urlpatterns = format_suffix_patterns(urlpatterns)

xyzshopping/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views as home_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.conf.urls import handler404, handler500
from tickets import views as ticket_views
from tickets import views
from xyzshopping import views as common_view
from .views import Comming_soon
# handler404 = 'common_view.custom_404'

urlpatterns = [
    path('hitcount/', include('hitcount.urls'), name='hitcount'),
    path('admin/', admin.site.urls),
    path('', include('tickets.urls')),
    path('visitors/home/', ticket_views.ticket_filter, name='home_view'),
    path('', Comming_soon, name='comming_soon'),
    path('team/', ticket_views.About_us.as_view(), name='about_us'),
    path('blog/', ticket_views.Blog.as_view(), name='blog'),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
    # path('tinymce/', include('tinymce.urls')),
    path('profile/', accounts_views.Profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    # path('listview/', Ticket_ListView, name='lists'),
    # path('api/chart/data/', ChartData.as_view(), name='api-chart-data'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Agatike - Administration'

tickets/forms.py
from django import forms
from django_countries.fields import CountryField

from allauth.account.forms import SignupForm

payment_choices = (
    ('MTN', 'MTN MOBILE MONEY'),
    ('AIRTEL', 'AIRTEL MONEY')
)

class CheckOut(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'ex: John'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'ex: Doe'
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'example@gmail.com'
    }))
    city = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'ex: Kigali'
    }))
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=payment_choices)
    country = CountryField(blank_label='(select country)').formfield()
    phone_number = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder': '+250 780 000 000'
    }))
    save_info = forms.BooleanField(widget=forms.CheckboxInput())


# class SignupForm(forms.ModelForm):
#     names = forms.CharField(max_length=30)
#     email = forms.CharField(max_length=30)
#
#     class Meta:
#         model = AbstractComprehensiveUser
#         fields = (
#             # Field to differentiate from buyer and seller
#             # user sign up
#             'user_type',
#             # Common fields for either buyer and seller
#             'names', 'email',
#             # seller specifc fields
#             'telephone_number', 'address', # etc etc
#         )
#
#
# class BuyerSignupForm(forms.ModelForm):
#     first_name = forms.CharField(max_length=30)
#     last_name = forms.CharField(max_length=30)
#
#     class Meta:
#         model = Buyer
#         fields = ('first_name', 'last_name')
#
#
# class SellerSignupForm(SignupForm):
#     company_name = forms.CharField(max_length=50, required=True, strip=True)
#
#     def save(self, request):
#         user = super(SellerSignupForm, self).save(request)
#         agatike_seller = Seller(
#             seller_person=user,
#             seller_name=self.cleaned_data.get('seller_name')
#         )
#         agatike_seller.save()
#         return agatike_seller.contact_person

tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http.response import HttpResponse
from django.views import generic
from django.contrib import messages
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ticket, AddedTicket, Added, Category

from .forms import CheckOut
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import TicketSerializers


class TicketsApi(APIView):
    
    def get(self, request):
        ticket = Ticket.objects.all()
        serializer = TicketSerializers(ticket, many=True)
        return Response(serializer.data)
    def post(self):
        pass



def index_ticket_view(request):
    tickets = Ticket.objects.all().order_by('-ticket_added_time')
    page = request.GET.get('page', 1)

    paginator = Paginator(tickets, 3)
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'tickets': tickets})



class Ticket_list_view(generic.ListView):
    template_name = 'tickets/event_list.html'
    context_object_name = 'tickets_list'
    ordering = ['-ticket_added_time']
    paginate_by = 9

    def get_queryset(self):
        return Ticket.objects.all().order_by('-ticket_added_time')
#

class Create_ticket(LoginRequiredMixin, CreateView):
    model = Ticket
    fields = ('ticket_title', 'location', 'starting_hour', 'starting_date', 'ending_date', 'ending_hour', 'ticket_banner', 'price_1', 'price_2', 'ticket_name_1', 'ticket_name_2', 'quantity_1', 'quantity_2', 'bonus_1', 'bonus_2', 'ticket_description', 'category', 'currency', 'organizer_name', 'organizer_description')
    success_url = reverse_lazy('tickets:dashboard_affiliates')
    login_url = 'login'
    redirect_field_name = 'tickets:create_ticket'

class Ticket_details(generic.DetailView):
    model = Ticket
    template_name = 'tickets/event_details.html'
    context_object_name = 'tickets_detail'

def Category_detail(request, slug):
    template = 'tickets/category_detail.html'
    category = get_object_or_404(Category, slug=slug)
    tickets = Ticket.objects.filter(category=category)
    page = request.GET.get('page', 1)
    paginator = Paginator(tickets, 6)
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)
    context = {
        'category': category,
        'tickets': tickets,
    }
    return render(request, template, context)



class Update_ticket(LoginRequiredMixin, UpdateView):
    model = Ticket
    fields = ('ticket_title', 'location', 'starting_hour', 'starting_date', 'ending_date', 'ending_hour', 'ticket_banner', 'price_1', 'price_2', 'ticket_name_1', 'ticket_name_2', 'quantity_1', 'quantity_2', 'bonus_1', 'bonus_2', 'ticket_description', 'category', 'currency', 'organizer_name', 'organizer_description')
    success_url = reverse_lazy('tickets:list_view')

class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Added.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'tickets/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "you do not have an active order")
            return redirect('tickets:list_view')

        # return render(self.request, 'tickets/order_summary.html')



class Delete_ticket(LoginRequiredMixin, DeleteView):
    model = Ticket
    success_url = reverse_lazy('tickets:list_view')



class Affiliate_help(generic.ListView):
    model = Ticket
    template_name = 'tickets/affiliate_help.html'
    context_object_name = 'affiliate_help'


class About_us(generic.ListView):
    model = Ticket
    template_name = 'tickets/About.html'
    context_object_name = 'about_us'

class Blog(generic.ListView):
    model = Ticket
    template_name = 'tickets/Blog.html'
    context_object_name = 'blog'



class Main_help(generic.ListView):
    model = Ticket
    template_name = 'tickets/help.html'
    context_object_name = 'main_help'


class CheckOutView(View):
    def get(self, *args, **kwargs):
        form = CheckOut()
        context = {
            'form': form
        }
        return render(self.request, "tickets/checkout.html", context)
    def post(self, *args, **kwargs):
        form = CheckOut(self.request.POST or None)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            city = form.cleaned_data.get('city')
            payment_option = form.cleaned_data.get('payment_option')
            country = form.cleaned_data.get('country')
            save_info = form.cleaned_data.get('save_info')
            phone_number = form.cleaned_data.get('phone_number')
            print('this form is valid')
            return redirect('tickets:checkout')
        messages.warning(self.request, "Failed to checkout")
        return redirect('tickets:checkout')


@login_required
def add_to_cart(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)
    order_ticket, created = AddedTicket.objects.get_or_create(
        tickets=ticket,
        user=request.user,
        ordered=False)
    added_qs = Added.objects.filter(user=request.user, ordered=False)
    if added_qs.exists():
        order = added_qs[0]
        if order.tickets.filter(tickets__pk=ticket.pk).exists():
            order_ticket.quantity += 1
            order_ticket.save()
            messages.info(request, "this Ticket quantity was updated.")
        else:
            # order = Added.objects.create(user=request.user)
            order.tickets.add(order_ticket)
    else:
        ordered_date = timezone.now()
        order = Added.objects.create(
                user=request.user,
                ordered_date=ordered_date,
            )
        order.tickets.add(order_ticket)
        messages.info(request, "this Ticket added to cart.")

    return redirect("tickets:order-summary")


def remove_to_cart(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)
    added_qs = Added.objects.filter(user=request.user, ordered=False)
    if added_qs.exists():
        order = added_qs[0]
        if order.tickets.filter(tickets__pk=ticket.pk).exists():
            order_ticket = AddedTicket.objects.filter(
                tickets=ticket,
                user=request.user,
                ordered=False)[0]
            order.tickets.remove(order_ticket)
            messages.info(request, "Ticket removed from cart.")
        else:
            messages.info(request, "this item was not in the cart.")
            return redirect("tickets:list_view")
    else:
        return redirect("tickets:list_view")
    return redirect("tickets:order-summary")



def remove_single_ticket_to_cart(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)

    added_qs = Added.objects.filter(user=request.user, ordered=False)
    if added_qs.exists():
        order = added_qs[0]
        if order.tickets.filter(tickets__pk=ticket.pk).exists():
            order_ticket = AddedTicket.objects.filter(
                tickets=ticket,
                user=request.user,
                ordered=False)[0]
            if order_ticket.quantity > 1:
                order_ticket.quantity -= 1
                order_ticket.save()
            else:
                order.tickets.remove(order_ticket)
                messages.info(request, "Ticket quantity was updated.")
            return redirect('tickets:order-summary')
        else:
            messages.info(request, "this item was not in the cart.")
            return redirect("tickets:order-summary")
    else:
        return redirect("tickets:order-summary")


def is_valid_queryparam(param):
    return param != '' and param is not None

def ticket_list_filter(request):
    qs = Ticket.objects.all().order_by('-ticket_added_time')
    # page = request.GET.get('page', 1)
    # paginator = Paginator(qs, 9)
    # try:
    #     qs = paginator.page(page)
    # except PageNotAnInteger:
    #     qs = paginator.page(1)
    # except EmptyPage:
    #     qs = paginator.page(paginator.num_pages)

    title_name = request.GET.get('title_contain')
    ticket_min_price_query = request.GET.get('min_price')
    ticket_max_price_query = request.GET.get('max_price')

    if is_valid_queryparam(title_name):
        qs = qs.filter(ticket_title__icontains=title_name)

    if is_valid_queryparam(ticket_min_price_query):
        qs = qs.filter(ticket_price__gte=ticket_min_price_query)

    if is_valid_queryparam(ticket_max_price_query):
        qs = qs.filter(ticket_price__lte=ticket_max_price_query)

    return render(request, 'tickets/event_list.html', {'queryset': qs})



def ticket_filter(request):
    qs = Ticket.objects.all().order_by('-ticket_added_time')
    # page = request.GET.get('page', 1)
    # paginator = Paginator(qs, 3)
    # try:
    #     qs = paginator.page(page)
    # except PageNotAnInteger:
    #     qs = paginator.page(1)
    # except EmptyPage:
    #     qs = paginator.page(paginator.num_pages)

    ticket_name_query = request.GET.get('ticket_name')
    ticket_location_query = request.GET.get('ticket_location')

tickets/templates/tickets/category_detail.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}All Ticket List{% endblock %}
{% block body %}

<div class="w-100 relative">
        <div class="w-100 mx-auto xl:flex px-2 ">
            <div class="w-20 xl:mx-2 pt-4 xs:hidden">
                <div class="sticky h-px-450 bor-rig px-4 mt-5">
                   <h1 class="text-grey-darkest text-2xl">Categories</h1>

                <ul class="list block text-grey-darkest pt-1 pl-2 pt-4">
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_concert' %}">Concert</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_festival' %}">Festival</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_cinema' %}">Cinema</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_sport' %}">Sport</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_expo' %}">Expo</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_meeting' %}">Meeting</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_others' %}">Others</a></li>
                </ul>
                </div>
            </div>
            <div class="pt-2">
                <h1 class="text-2xl ">Results for {{ category.name }}:</h1>
                </div>
                <div class="py-1 xl:grid-3 grid pt-4 bg-white" style="grid-template-columns: repeat(1, 1fr);">

                {% if tickets %}
                {% for ticket in tickets %}
                    <div class="xl:mx-2 xs:w-100 my-2 bg-white-smoke px-2 py-2 hover:shadow-lg border rounded relative">
                        <a href="{%  url 'tickets:ticket_detail' ticket.pk%}">
                            <div class="xl:hidden md:hidden" style="height: 150px">
                            <img class="clip-full" src="{{ ticket.ticket_banner.url}}">
                            </div>
                            <div class="xs:hidden" style="height: 250px">
                            <img class="clip-full" src="{{ ticket.ticket_banner.url}}">
                            </div>
                        </a>
                        <div class="py-2 flex relative bg-white-smoke text-black">
                            <div class="w-20 my-auto">
                                <div class="w-100 pt-1 border-solid border-1 border-black text-center pb-1">
                                    <span class="text-sm">{{ ticket.starting_date }}</span>
                                </div>
                            </div>
                            <div class="w-80 mx-2 text-black">
                                <span class="text-sm font-semibold"><a class="text-black" href="{%  url 'tickets:ticket_detail' ticket.pk%}">{{ ticket.snippet}} </a></span>
                                <p class="line-height-small text-sm pt-1">{{ ticket.starting_hour }} Up To {{ ticket.ending_hour }}</p>
                            </div>
                            <a class="btn absolute btn-sm r-0 b-0 bg-orange text-white" href="{%  url 'tickets:ticket_detail' ticket.pk%}"><i class="fas fa-shopping-basket"></i> Buy</a>
                        </div>

                    </div>
                    {% endfor %}
                {% else %}
                   <h1 class="text-2xl">Sorry! No {{ category.name }} tickets Available</h1>
                {% endif %}


                </div>
            <div class="w-50 float-right text-centered mt-5">
                        {% if queryset.has_other_pages %}
                          <ul class="pagination">
                            {% if queryset.has_previous %}
                              <li><a href="?page={{ queryset.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in queryset.paginator.page_range %}
                              {% if users.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if queryset.has_next %}
                              <li><a href="?page={{ queryset.next_page_number }}">&raquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                          </ul>
                        {% endif %}
    </div>
            </div>
        </div>
</div>
{% endblock %}

tickets/templates/tickets/data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tickets/templates/tickets/event_list.html
{% extends 'base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}All Ticket List{% endblock %}
{% block body %}

<div class="w-100 relative">
        <div class="w-100 mx-auto xl:flex md:flex px-2 ">
            <div class="w-20 xl:mx-2 pt-4 xs:hidden">
                <div class="sticky h-px-450 bor-rig px-4 mt-5">
                   <h1 class="text-grey-darkest text-2xl">Categories</h1>

                <ul class="list block text-grey-darkest pt-1 pl-2 pt-4">
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_concert' %}">Concert</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_festival' %}">Festival</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_cinema' %}">Cinema</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_sport' %}">Sport</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_expo' %}">Expo</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_meeting' %}">Meeting</a></li>
                        <li class="my-2"><a class="text-grey-darkest" href="{% url 'tickets:category_others' %}">Others</a></li>
                </ul>
                </div>
            </div>
            <div class="w-90 xs:w-100 xl:mx-4 pt-3">
                <div class="flex w-100 xs:hidden">
                    <div class="w-20">
                        <span class="pl-2 text-xl">All Tickets: </span>
                    </div>
                    <div class="w-80 text-center bg-white-smoke rounded-b-xxl shadow-sm -mt-4 py-2">
                        <form method="get" class="">
                            <div class="flex w-100">
                                <div class="md:hidden w-20"></div>
                                <div class="w-20 md:w-30 text-left mx-3">
                                <span class="text-sm">Minimum Price:</span>
                                <input class="form-input rounded" type="number" name="min_price" placeholder="ex : 0">
                                </div>
                                <div class="w-10 text-center mt-4 pt-1">
                                    <p>Up To</p>
                                </div>
                                <div class="w-20 md:w-30 text-left mx-3">
                                    <span class="text-sm">Maximum Price:</span>
                                    <input class="form-input rounded" type="number" name="max_price" placeholder="ex : 5000">
                                </div>
                                <div class="w-20 pt-4 r-0">
                                    <button class="btn w-90 rounded-full -ml-5 bg-orange text-white py-1">
                                        Search
                                    </button>
                                </div>
                                <div class="w-10">

                                </div>
                            </div>
                        </form>
                    </div>


                </div>
                <div class="py-1 xl:grid-3 md:grid-2 grid pt-4 bg-white md:pl-2" style="grid-template-columns: repeat(1, 1fr);">

                {% if queryset %}
                    {% for ticket in queryset %}
                    <div class="xl:mx-2 xs:w-100 md:mx-1 my-2 bg-white-smoke px-2 py-2 hover:shadow-lg border rounded relative">
                        <a href="{%  url 'tickets:ticket_detail' ticket.pk%}">
                            <div class="xl:hidden md:hidden" style="height: 150px">
                            <img class="clip-full" src="{{ ticket.ticket_banner.url}}">
                            </div>
                            <div class="xs:hidden md:hidden" style="height: 250px">
                            <img class="clip-full" src="{{ ticket.ticket_banner.url}}">
                            </div>
                            <div class="xs:hidden xl:hidden" style="height: 150px">
                            <img class="clip-full" src="{{ ticket.ticket_banner.url}}">
                            </div>
                        </a>
                        <div class="py-2 flex relative bg-white-smoke text-black">
                            <div class="w-20 my-auto">
                                <div class="w-100 pt-1 border-solid border-1 border-black text-center pb-1">
                                    <span class="text-sm">{{ ticket.starting_date }}</span>
                                </div>
                            </div>
                            <div class="w-80 mx-2 text-black">
                                <span class="text-sm font-semibold"><a class="text-black" href="{%  url 'tickets:ticket_detail' ticket.pk%}">{{ ticket.snippet}} </a></span>
                                <p class="line-height-small text-sm pt-1">{{ ticket.starting_hour }} Up To {{ ticket.ending_hour }}</p>
                            </div>
                            <a class="btn absolute btn-sm r-0 b-0 bg-orange text-white" href="{%  url 'tickets:ticket_detail' ticket.pk%}"><i class="fas fa-shopping-basket"></i> Buy</a>
                        </div>

                    </div>
                    {% endfor %}
                {% else %}
                    <h1 class="text-2xl">Sorry! No tickets Available</h1>
                {% endif %}


                </div>
            <div class="w-50 float-right text-centered mt-5">
                        {% if queryset.has_other_pages %}
                          <ul class="pagination">
                            {% if queryset.has_previous %}
                              <li><a href="?page={{ queryset.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in queryset.paginator.page_range %}
                              {% if users.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if queryset.has_next %}
                              <li><a href="?page={{ queryset.next_page_number }}">&raquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                          </ul>
                        {% endif %}
    </div>
            </div>
        </div>
</div>
{% endblock %}

tickets/templates/tickets/qr-code.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load qr_tags %}

{% block title %}Qr-Code Test{% endblock %}
{% block body %}
    <div>
        {% qr_from_object object "size" %}
        <img src="http://chart.apis.google.com/chart?cht=qr&chs={{ size }}x{{ size }}&chl={{ text }}" />
    </div>
{% endblock %}

tickets/templates/tickets/ticket_confirm_delete.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %}delete | {{ ticket.event_name }}{% endblock %}
{% block body %}
    <div class="w-60 mx-auto mt-16">
        <div class="w-50 mx-auto p-2">
            <div class="h-px-400">
                <img class="clip-full" src="{{ ticket.event_banner.url }}">
            </div>
            <div class="bg-black-darker p-2 text-white">
                <span>{{ ticket.event_name }}</span>
                <p>{{ ticket.event_starting_date }} - {{ ticket.event_ending_date }}</p>
                <form method="post">
                    {% csrf_token %}
                    <input class="btn-danger btn w-40 ml-4" type="submit" value="Confirm">
                    <a class="w-40 btn bg-white border-1 border-accent" href="{% url 'tickets:list_view' %}">Cancel</a>
                </form>

            </div>
        </div>
    </div>
{% endblock %}