accounts/urls.py
from django.urls import path
from .views import Register

app_name = 'accounts'

urlpatterns = [
    path('register/', Register, name='register')
]

tickets/urls.py
from django.urls import path
from .import views
from .views import add_to_cart, remove_to_cart, remove_single_ticket_to_cart, Category_detail, ChartData
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'tickets'

urlpatterns = [
    # ticket/api/view/
    path('tickets/api/view/', views.TicketsApi.as_view()),
    # tickets/list/
    path('all-tickets/', views.ticket_list_filter, name='list_view'),
    # tickets/affiliate/help/
    path('affiliate/help/', views.Affiliate_help.as_view(), name='affiliate_help'),
    # # tickets/team/
    # path('team/', views.About_us.as_view(), name='team'),
    # # tickets/team/
    # path('blog/', views.Blog.as_view(), name='blog'),
    # tickets/5/details/
    path('<int:pk>/details/', views.Ticket_details.as_view(), name='ticket_detail'),
    # tickets/create/
    path('create/', views.Create_ticket.as_view(), name='create_ticket'),
    # tickets/5/update/
    path('<int:pk>/update/', views.Update_ticket.as_view(), name='update_ticket'),
    # tickets/5/delete/
    path('<int:pk>/delete/', views.Delete_ticket.as_view(), name='delete_ticket'),
    # tickets/help/affiliate/
    path('help/', views.Main_help.as_view(), name='main_help'),
    # tickets/add/cart/
    path('<int:pk>/add/cart/', add_to_cart, name='add_cart'),
    # tickets/remove/cart/
    path('<int:pk>/remove/cart/', remove_to_cart, name='remove_cart'),
    #tickets/order-summary/
    path('order/summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    # tickets/remove/cart/
    path('<int:pk>/remove/ticket/cart/', remove_single_ticket_to_cart, name='remove_single_ticket_cart'),
    #tickets/checkout/
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    #category/cinema/
    path('category/<str:slug>/', Category_detail, name='category'),
    path('category/cinema/', Category_detail, name='category_cinema'),
    path('category/sport/', Category_detail, name='category_sport'),
    path('category/concert/', Category_detail, name='category_concert'),
    path('category/expo/', Category_detail, name='category_expo'),
    path('category/meeting/', Category_detail, name='category_meeting'),
    path('category/others/', Category_detail, name='category_others'),
    path('category/festival/', Category_detail, name='category_festival'),
    path('api/data/', ChartData.as_view(), name='dash-api'),
    path('dashboard/', views.DashView.as_view(), name='dashboard_affiliates'),



]

urlpatterns = format_suffix_patterns(urlpatterns)

xyzshopping/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views as home_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.conf.urls import handler404, handler500
from tickets import views as ticket_views
from tickets import views
from xyzshopping import views as common_view
from .views import Comming_soon
# handler404 = 'common_view.custom_404'

urlpatterns = [
    path('hitcount/', include('hitcount.urls'), name='hitcount'),
    path('admin/', admin.site.urls),
    path('', include('tickets.urls')),
    path('visitors/home/', ticket_views.ticket_filter, name='home_view'),
    path('', Comming_soon, name='comming_soon'),
    path('team/', ticket_views.About_us.as_view(), name='about_us'),
    path('blog/', ticket_views.Blog.as_view(), name='blog'),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('allauth.urls')),
    # path('tinymce/', include('tinymce.urls')),
    path('profile/', accounts_views.Profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    # path('listview/', Ticket_ListView, name='lists'),
    # path('api/chart/data/', ChartData.as_view(), name='api-chart-data'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Agatike - Administration'

tickets/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser

class Included(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
#
# class TicketType(models.Model):
#     name = models.CharField(max_length=50)
#     # price = models.FloatField()
#     # limit = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return '%s ($%.2f)' % (self.name, self.price)


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Ticket(models.Model):
    ticket_title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    ticket_added_time = models.DateTimeField(auto_now=True)
    starting_hour = models.TimeField()
    ending_hour = models.TimeField()
    ending_date = models.DateField()
    ticket_banner = models.FileField(default='default.jpg')
    ticket_description = models.TextField(max_length=10000)
    # ticket_price = models.FloatField(max_length=250)
    # ticket_type = models.ForeignKey(TicketType, on_delete=models.CASCADE, null=True, blank=True)
    ticket_name_1 = models.CharField(max_length=100)
    price_1 = models.FloatField()
    quantity_1 = models.IntegerField()
    bonus_1 = models.CharField(max_length=60, blank=True, null=True)
    ticket_name_2 = models.CharField(max_length=100, null=True, blank=True)
    price_2 = models.FloatField(null=True, blank=True)
    quantity_2 = models.IntegerField(null=True, blank=True)
    bonus_2 = models.CharField(max_length=60, blank=True, null=True)
    ticket_name_3 = models.CharField(max_length=100, null=True, blank=True)
    price_3 = models.FloatField(null=True, blank=True)
    quantity_3 = models.IntegerField(null=True, blank=True)
    bonus_3 = models.CharField(max_length=60, blank=True, null=True)
    price_choices = (
        ('ticket', ''),
    )
    currency_choices = (
        ('RWF', 'RWF'),
    )
    currency = models.CharField(max_length=100, default='choose', choices=currency_choices)
    # seller_name = models.ForeignKey(UserManagement, on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    starting_date = models.DateField()
    organizer_name = models.CharField(max_length=100, null=True, blank=True)
    organizer_description = models.TextField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.ticket_title

    def snippet(self):
        return self.ticket_title[:20] + '...'

    def get_absolute_url(self):
        return reverse('tickets:list_view', kwargs={
            'pk': self.pk
        })

    def get_add_to_cart_url(self):
        return reverse('tickets:add_cart', kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart(self):
        return reverse('tickets:remove_cart', kwargs={
            'pk': self.pk
        })


class AddedTicket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    tickets = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    # ticket_types = models.ManyToManyField(TicketTypes)

    def __str__(self):
        return f"{self.quantity} of {self.tickets.ticket_title}"

    # def get_total_ticket_price(self):
    #     return self.quantity * self.tickets.
    #
    # def get_final_price(self):
    #     return self.get_total_ticket_price()

    def tickets_available(self):
        return max(self.quantity - self.tickets.objects.count(), 0)


class Added(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tickets = models.ManyToManyField(AddedTicket)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    # def get_total(self):
    #     total = 0
    #     for added_ticket in self.tickets.all():
    #         total += added_ticket.get_final_price()
    #     return total


# class TicketPurchase(models.Model):
#     email = models.EmailField(default='', verbose_name="email")
#     name = models.CharField(max_length=100)
#     date = models.DateField(auto_now_add=True, editable=False)
#     amount = models.FloatField()
    status = models.CharField(default='pending', max_length=20)

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.status)

    def paid(self):
        return "completed" in self.status

    def invoice(self):
        return self.id

templates/base.html
{% load staticfiles %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/style.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/mobile.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/tablet.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/desktop.css' %}">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/fonts/_flaticon.css' %}">

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{% static 'tickets/image/favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'tickets/image/favicon.png' %}" type="image/x-icon">
    <style>
        .bg-team{
            background-image: url({% static 'tickets/image/bg1.jpg' %});
            background-size: cover;
            height: 400px;
            width: 100%;
            padding-top: 7em;
        }
        h1, span{
            font-family: 'Lato', sans-serif;
        }
        .bor-bot{
            border-bottom: .2px solid white;
        }
        .bor-lef{
            border-left: 1px solid white;
        }
        .bor-rig{
            border-right: 1px solid grey;
        }
        .backgroun_img{
            background-image: url("{% static 'tickets/image/homebackg.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .form-text{
            display: none;
        }
        .bg{
          background-image: url("{% static 'tickets/image/img (51).jpg' %}");
          background-repeat: no-repeat;
            background-size: cover;
            height: 350px;
        }

    </style>
</head>
<body class="w-100 xs:w-100 md:w-100 overflow-x-hidden">
<div class="w-100 bg-white z-9999 xs:hidden md:hidden shadow sticky">
    <div class="w-90 mx-auto flex py-2">
        <div class="w-20">
           <img class="w-15 mx-2" src="{% static 'tickets/image/logo.png' %}"> <span class=" text-white"><a href="{% url 'home_view' %}" class="text-black no-underline text-2xl">Agatike </a></span>
        </div>
        <div class="w-25 mt-1">

        </div>
        <div class="w-55 text-right pr-4 xs:hidden">
            <ul class="list inline-block text-white nav nav-pills">
            <li class="text-base mx-4">
                <a class="text-black" href="{% url 'tickets:list_view' %}">All tickets</a>
            </li>
            <li class="text-base  mx-4">
                <a class="text-black" href="{% url 'tickets:create_ticket' %}">Create Ticket</a>
            </li>
            <li class="text-base  mx-4">
                <a class="text-black" href="{% url 'tickets:main_help' %}">Help</a>
            </li>
            {% if user.is_authenticated %}
            <li class="text-base  mx-4">
                <a class="text-black no-underline" href="{% url 'tickets:order-summary' %}">
                    Cart<span class="bg-orange px-2 py-1 rounded-full text-white">{{ request.user|cart_item_count }}</span></a>
            </li>
            <li class="nav-item dropdown mx-4 -mt-1">
              <a class="dropdown-toggle rounded-circle text-black" href="#" id="navbardrop" data-toggle="dropdown">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
              </a>
              <div class="dropdown-menu mt-3 mr-3">
                    <a class=" dropdown-item " href="{% url 'profile' %}"><i class="ml-2 mx-2" data-feather="user"></i>{{ user.username }}</a>
                    <a class=" dropdown-item" href="{% url 'logout' %}"> <i class="ml-2 mx-2" data-feather="log-out"></i>Logout</a>

              </div>
            </li>
            {% else %}
             <li class="text-base  mx-3">
                <a class="text-black" href="{% url 'accounts:register' %}">Sign up</a>
            </li>
            {% endif %}
{#                    {% if user.is_authenticated %}#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'profile' %}">{{ user.username }}</a></li>#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'logout' %}">Logout</a></li>#}
{#                    {% else %}#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'login' %}">Login</a></li>#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'accounts:register' %}">Signup</a></li>#}
{#                    {% endif %}#}
        </ul>
        </div>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-centered" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endfor %}
{% endif %}
{% block body %}
{% endblock %}
<div class="b-0 w-100 xs:hidden bg-black-darker mt-24 z-50 relative">
    <div class="w-80 mx-auto px-5 py-5">
        <div class="border-top border-bottom border-white pt-2 pb-4 px-5 text-center">
            <ul class="list inline-block text-white">
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'blog' %}">Blog</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'tickets:main_help' %}">Help</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'about_us' %}">Team</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg">Cookies</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'about_us' %}">Services</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg">Developers</a></li>
            </ul>
        </div>
    <div class="w-100 absolute pt-2 text-center">
       <p class=" text-white">© 2019 </p>
    </div>
    </div>

<script>
      feather.replace()
</script>
<script>
        $('#id_starting_date').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
</script>
<script>
        $('#id_ending_date').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
</script>

 <script>
        $('#id_starting_hour').timepicker({ uiLibrary: 'bootstrap4' });
 </script>
    <script>
        $('#id_ending_hour').timepicker({ uiLibrary: 'bootstrap4' });
 </script>



</div>

</body>
</html>

templates/base_layout.html
{% load staticfiles %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/style.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/mobile.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/tablet.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/desktop.css' %}">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
     <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/fonts/_flaticon.css' %}">

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{% static 'tickets/image/favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'tickets/image/favicon.png' %}" type="image/x-icon">

    <style>
        .bg-team{
            background-image: url({% static 'tickets/image/bg1.jpg' %});
            background-size: cover;
            height: 400px;
            width: 100%;
            padding-top: 7em;
        }
        h1, span{
            font-family: 'Lato', sans-serif;
        }
        .bor-bot{
            border-bottom: .2px solid white;
        }
        .bor-lef{
            border-left: 1px solid white;
        }
        .bor-rig{
            border-right: 1px solid grey;
        }
        .backgroun_img{
            background-image: url("{% static 'tickets/image/homebackg.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .form-text{
            display: none;
        }
        .bg{
          background-image: url("{% static 'tickets/image/img (51).jpg' %}");
          background-repeat: no-repeat;
            background-size: cover;
            height: 350px;
        }

    </style>
</head>
<body class="w-100 xl:w-100 xs:w-100 md:w-100 overflow-x-hidden">
<div class="w-100 bg-black-darker z-9999 shadow xs:hidden">
    <div class="w-90 mx-auto flex py-2">
        <div class="w-20">
            <span class=" text-white"><a href="{% url 'home_view' %}" class="text-white no-underline text-2xl"><img class="w-15 mx-2" src="{% static 'tickets/image/logo-orange.png' %}">Agatike </a></span>
        </div>
        <div class="w-25 mt-1">
            <form class="form-inline" method="get">
                <input class="form-input bg-white  border-b-1 w-85 rounded" name="title_contain" type="search" placeholder="search ticket name..">
                <button class="btn w-15 bg-orange text-white rounded -ml-1" type="submit"><i class="fi flaticon-search-1"></i></button>
            </form>
        </div>
        <div class="w-55 text-right pr-4">
            <ul class="list inline-block text-white nav nav-pills">
            <li class="text-base mx-4">
                <a class="text-white" href="{% url 'tickets:list_view' %}">All tickets</a>
            </li>
            <li class="text-base  mx-4">
                <a class="text-white" href="{% url 'tickets:create_ticket' %}">Create Ticket</a>
            </li>
            <li class="text-base  mx-4">
                <a class="text-white" href="{% url 'tickets:main_help' %}">Help</a>
            </li>
            {% if user.is_authenticated %}
            <li class="text-base  mx-4">
                <a class="text-white no-underline" href="{% url 'tickets:order-summary' %}">
                    Cart<span class="bg-orange px-2 py-1 rounded-full">{{ request.user|cart_item_count }}</span>
                </a>
            </li>
            <li class="nav-item dropdown mx-4 -mt-1">
              <a class="dropdown-toggle rounded-circle text-white" href="#" id="navbardrop" data-toggle="dropdown">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
              </a>
              <div class="dropdown-menu mt-3 mr-3">
                    <a class=" dropdown-item " href="{% url 'profile' %}"><i class="ml-2 mx-2" data-feather="user"></i>{{ user.username }}</a>
                    <a class=" dropdown-item" href="{% url 'logout' %}"> <i class="ml-2 mx-2" data-feather="log-out"></i>Logout</a>

              </div>
            </li>
            {% else %}
             <li class="text-base  mx-3">
                <a class="text-white" href="{% url 'accounts:register' %}">Sign up</a>
            </li>
            {% endif %}
{#                    {% if user.is_authenticated %}#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'profile' %}">{{ user.username }}</a></li>#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'logout' %}">Logout</a></li>#}
{#                    {% else %}#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'login' %}">Login</a></li>#}
{#                        <li class="mx-4 text-base"><a class="text-white" href="{% url 'accounts:register' %}">Signup</a></li>#}
{#                    {% endif %}#}
        </ul>
        </div>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-centered" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

    {% endfor %}
{% endif %}
<div class="md:hidden xl:hidden relative z-99">
    <div class="fixed w-100 h-px-40 b-2">
        <div class="w-100 absolute bg-white z-99 py-2  pt-2 shadow-lg">
        <div class="w-80 mx-auto">
           <ul class="list inline-block text-center">
            <li class="mx-3"><i class="fas fa-home text-2xl"></i></li>
            <li class="mx-3"><i class="fas fa-bars text-2xl"></i></li>
            <li class="mx-3"><i class="far fa-plus-square text-2xl"></i></li>
            <li class="mx-3"><i class="fas fa-shopping-basket text-2xl"></i><span class="bg-orange px-2 rounded-full -ml-3 -mt-2 text-white absolute">{{ request.user|cart_item_count }}</span></li>
{#            <li class="mx-3"><i class="far fa-user text-2xl"></i></li>#}
            </ul>
        </div>

    </div>
    </div>

</div>
{% block body %}

{% endblock %}

<div class="b-0 w-100 bg-black-darker mt-24 z-50 relative xs:hidden">
    <div class="w-80 mx-auto px-5 py-5">
        <div class="border-top border-bottom border-white pt-2 pb-4 px-5 text-center">
            <ul class="list inline-block text-white">
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'blog' %}">Blog</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'tickets:main_help' %}">Help</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'about_us' %}">Team</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg">Cookies</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg" href="{% url 'about_us' %}">Services</a></li>
                <li class="mx-3 text-lg"><a class="text-white text-lg">Developers</a></li>
            </ul>
        </div>
    <div class="w-100 absolute pt-2 text-center">
       <p class=" text-white">© 2019 </p>
    </div>
    </div>

<script>
      feather.replace()
</script>
<script>
        $('#id_starting_date').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
</script>
<script>
        $('#id_ending_date').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
</script>
 <script>
     $('#id_ticket_description').editor({
         uiLibrary: 'bootstrap4'
     });
 </script>
    <script>
     $('#id_organizer_description').editor({
         uiLibrary: 'bootstrap4'
     });
 </script>
 <script>
        $('#id_starting_hour').timepicker({ uiLibrary: 'bootstrap4' });
 </script>
    <script>
        $('#id_ending_hour').timepicker({ uiLibrary: 'bootstrap4' });
 </script>

</div>

</body>
</html>